import { Product } from './store';

export const allProducts: Product[] = [
  {
    id: '1',
    name: 'Nordic Lounge Chair',
    price: 349.99,
    category: 'Chair',
    image: 'https://picsum.photos/seed/chair1/800/1000',
    rating: 4.8,
    description: 'Minimalist lounge chair with premium fabric and solid oak wood legs.',
  },
  {
    id: '2',
    name: 'Velvet Cloud Sofa',
    price: 1299.00,
    category: 'Sofa',
    image: 'https://picsum.photos/seed/sofa1/800/1000',
    rating: 4.9,
    description: 'Luxurious 3-seater velvet sofa with deep seating and plush cushions.',
  },
  {
    id: '3',
    name: 'Marble Dining Table',
    price: 899.50,
    category: 'Table',
    image: 'https://picsum.photos/seed/table1/800/1000',
    rating: 4.7,
    description: 'Elegant round dining table featuring a genuine marble top and brass base.',
  },
  {
    id: '4',
    name: 'Abstract Ceramic Vase',
    price: 85.00,
    category: 'Decor',
    image: 'https://picsum.photos/seed/decor1/800/1000',
    rating: 4.6,
    description: 'Handcrafted ceramic vase with a unique abstract shape and matte finish.',
  },
  {
    id: '5',
    name: 'Leather Executive Chair',
    price: 450.00,
    category: 'Chair',
    image: 'https://picsum.photos/seed/chair2/800/1000',
    rating: 4.5,
    description: 'Ergonomic leather chair perfect for your home office.',
  },
  {
    id: '6',
    name: 'Minimalist Platform Bed',
    price: 1100.00,
    category: 'Bed',
    image: 'https://picsum.photos/seed/bed1/800/1000',
    rating: 4.8,
    description: 'Sleek platform bed frame made from sustainable walnut wood.',
  },
  {
    id: '7',
    name: 'Modern Glass Coffee Table',
    price: 299.00,
    category: 'Table',
    image: 'https://picsum.photos/seed/table2/800/1000',
    rating: 4.4,
    description: 'Tempered glass coffee table with a geometric metal base.',
  },
  {
    id: '8',
    name: 'Woven Wall Art',
    price: 120.00,
    category: 'Decor',
    image: 'https://picsum.photos/seed/decor2/800/1000',
    rating: 4.7,
    description: 'Large macrame wall hanging to add texture to any room.',
  },
  {
    id: '9',
    name: 'L-Shaped Sectional Sofa',
    price: 1899.00,
    category: 'Sofa',
    image: 'https://picsum.photos/seed/sofa2/800/1000',
    rating: 4.9,
    description: 'Spacious sectional sofa perfect for large families and entertaining.',
  },
  {
    id: '10',
    name: 'Upholstered Queen Bed',
    price: 950.00,
    category: 'Bed',
    image: 'https://picsum.photos/seed/bed2/800/1000',
    rating: 4.6,
    description: 'Queen bed with a tufted fabric headboard for ultimate comfort.',
  },
  {
    id: '11',
    name: 'Rustic Wooden Dining Set',
    price: 1499.00,
    category: 'Dining',
    image: 'https://picsum.photos/seed/dining1/800/1000',
    rating: 4.8,
    description: 'Complete dining set including a reclaimed wood table and 6 matching chairs.',
  },
  {
    id: '12',
    name: 'Brass Floor Lamp',
    price: 180.00,
    category: 'Decor',
    image: 'https://picsum.photos/seed/decor3/800/1000',
    rating: 4.5,
    description: 'Tall brass floor lamp with an adjustable reading light.',
  }
];
